default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>

development:
  <<: *default
  database: <%= ENV["DB_DATABASE"] %>

test:
  <<: *default
  database: <%= ENV["DB_DATABASE"] %>

production:
  <<: *default
  database: dahora_production
  username: dahora
  password: <%= ENV["DB_DATABASE"] %>