default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: db
  port: <%= ENV["DB_PORT"] %>
  socket: <%= ENV["DB_SOCKET"] %>

development:
  <<: *default
  database: <%= ENV["DB_DATABASE_DEV"] %>

test:
  <<: *default
  database: <%= ENV["DB_DATABASE_TEST"] %>

production:
  <<: *default
  database: rails_production
  username: rails
  password: <%= ENV["DB_DATABASE_PROD"] %>